### ISSUE TITLE
Hugemce - How to get it?

### ISSUE THREAD

**Issue by akissz** [hugemce/hugemce#6]
All well and good the idea of Hugemce. But the info text on your github doesn't explain how to get the normal zip file that has all the hugemce/tinymce files as usual with TinyMCE. Installing with NPM does not function. And all your links point to TinyMCE website. I understand you have the files here in github as something to compile or something, but this is not efficient way to provide a program to the public especially when you are not including instructions. The readme file also has zero info and again links to the TinyMCE website instead of what should be active hugemce.com. I am surprised it is this way with 17 people working on Hugemce now. ??? Explain the logic please.

**Comment by carlosmintfan** [comment]
Hi there, thank you for your interest in this project. HugeMCE can't be downloaded yet and actually there has almost been zero work done yet. Also, when I've tried to build it, I got some error that something doesn't exist. I'll try again later but I'm very busy with other things currently so it may still take some weeks. But it should be ready on NPM and Packagist before TinyMCE 6 is EOL, even if it's still almost the same as TinyMCE at that state. As this repo is a detached fork of TinyMCE, the 17 people are actually just those who have worked on TinyMCE, not HugeMCE. There's no such site as hugemce.com, I registered hugemce.org (HugeMCE is not commercial, org fits better) and I built a bad and tiny welcome page with a link to GitHub but before I can publish it, I am waiting for an answer from DeployHQ whether I can create a second free account for HugeMCE in addition to my existing account for non-opensource stuff.

**Comment by carlosmintfan** [comment]
You may watch this repo or subscripe to #1 to stay up to date.

**Comment by jcorradino** [comment]
@akissz - I don't quite know if there's something missing in there, but playing around with it myself.  I was able to just clone it into a git module in my react project (`git submodule add https://github.com/hugemce/hugemce.git src/hugemce`), and then install NPM packages ignoring dependency mismatches (`npm install --legacy-peer-deps`).

Seemed to work just fine when I imported it and used it in my react priject.

**Comment by carlosmintfan** [comment]
@jcorradino That‘s true, you can still stay with TinyMCE 6.x until I announce an npm version. This project still isn‘t better than free TinyMCE 6. However, it’s goal is to provide MIT-licensed updates after TinyMCE 6 has reached end of life, and in addition, I hope we can reimplement some of the paid plugins of TinyMCE. There has already been implemented a basic Paste from Word plugin. I hope it doesn‘t use code from one of the old releases of TinyMCE when clean pasting from Word was free. Because the code was LGPL-licensed then and we want our project to be MIT as much as possible. So I‘ll have to check the code, clean it up and integrate it into the HugeMCE core. That‘s one example for what I hope to get better in HugeMCE.
There may be a Beta phase during September, and then at end of September / Start of October it should be ready so everyone who wants can migrate from TinyMCE 6.
